name: emergency_app
description: Emergency call application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.4
  flutter_bloc: ^8.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/ambulance.png
    - assets/images/
    - assets/volunteer.jpg

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700

# ------------------------------
# 👇 THIS MUST BE OUTSIDE flutter:
# ------------------------------
gen_l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
