// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZ1m6ara4Ahy4NrZG4LUxr01UcBbL14o',
    appId: '1:475175597982:web:d7e9c8daf9d4f81b5d488f',
    messagingSenderId: '475175597982',
    projectId: 'allo-selekni-app',
    authDomain: 'allo-selekni-app.firebaseapp.com',
    storageBucket: 'allo-selekni-app.firebasestorage.app',
    measurementId: 'G-PGBKWJ1SR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJl4zlKfK9cLWEkL5k-Vz3xYKgd_OsRV4',
    appId: '1:475175597982:android:5ad114881c0ed2cd5d488f',
    messagingSenderId: '475175597982',
    projectId: 'allo-selekni-app',
    storageBucket: 'allo-selekni-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPO9cysq2-1RE-G4Vi4wVIv25vJEfeLs',
    appId: '1:475175597982:ios:2388c011e0bbb9f55d488f',
    messagingSenderId: '475175597982',
    projectId: 'allo-selekni-app',
    storageBucket: 'allo-selekni-app.firebasestorage.app',
    iosBundleId: 'com.example.page1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPO9cysq2-1RE-G4Vi4wVIv25vJEfeLs',
    appId: '1:475175597982:ios:2388c011e0bbb9f55d488f',
    messagingSenderId: '475175597982',
    projectId: 'allo-selekni-app',
    storageBucket: 'allo-selekni-app.firebasestorage.app',
    iosBundleId: 'com.example.page1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhZ1m6ara4Ahy4NrZG4LUxr01UcBbL14o',
    appId: '1:475175597982:web:c15a0e9b030106245d488f',
    messagingSenderId: '475175597982',
    projectId: 'allo-selekni-app',
    authDomain: 'allo-selekni-app.firebaseapp.com',
    storageBucket: 'allo-selekni-app.firebasestorage.app',
    measurementId: 'G-REYE3YE6D1',
  );
}
